---
- name: install pip
  apt: name=python-pip state=present
  tags:
    - install_pip

- name: install boto sdk
  pip: name=boto
  tags:
    - install_boto

- name: Create s3 bucket that  will hold the buckup database
  s3_bucket:
    name: "{{ AWS_S3_BUCKET_NAME }}"
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY}}"
    region: "{{ AWS_REGION }}"
  tags:
    - create_s3_bucket

- name: Build backup bash script
  template:
    src=backup.sh.j2
    dest={{ ansible_env.PWD }}/backup.sh
    mode=0755
    owner=ubuntu
  tags:
   - build_script

- name: Create a cron job to run the script on  host machine
  cron:
    name: "Backup Mysql database daily"
    special_time: daily
    user: ubuntu
    job: "{{ ansible_env.PWD }}/backup.sh"
    state: present
  tags:
    - cron_job
